# Generated by Django 4.1.3 on 2022-11-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cardset',
            table='omniflash_card_sets',
        ),
        migrations.AlterModelTable(
            name='favorite',
            table='omniflash_favorites',
        ),
        migrations.AlterModelTable(
            name='flashcard',
            table='omniflash_flashcards',
        ),
        migrations.AlterModelTable(
            name='user',
            table='omniflash_users',
        ),
    ]
