# Generated by Django 4.1.3 on 2022-11-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_setcategory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='setcategory',
            table='omniflash_set_category',
        ),
    ]
