# Generated by Django 4.1.3 on 2022-11-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_setcategory_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='setcategory',
            table=None,
        ),
    ]
