# Generated by Django 4.1.3 on 2022-11-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_setcategory_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SetCategory',
        ),
    ]
