# Generated by Django 4.1.3 on 2022-11-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_setcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardset',
            old_name='authorId',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='cardSetId',
            new_name='card_set',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='cardSetId',
            new_name='card_set',
        ),
        migrations.RenameField(
            model_name='setcategory',
            old_name='cardSetId',
            new_name='card_set',
        ),
        migrations.RenameField(
            model_name='setcategory',
            old_name='categoryId',
            new_name='category',
        ),
    ]
